# Exercices

With each exercice will teach you one aspect of deep learning.
The process of machine learning can be decompose in 7 steps :

0. Data acquisition
1. Data preparation
2. Model definition
3. Model training
4. Model evaluation
5. Hyperparameter tuning
6. Prediction

In [1]:
from __future__ import print_function
import torch

## 2 - Model definition

from https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html


### Tensors

#### Initialization of tensors

In [5]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00,  3.6893e+19, -2.9298e+25],
        [ 4.6577e-10,  7.0065e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [6]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7899, 0.8925, 0.1289],
        [0.6076, 0.8531, 0.2062],
        [0.3443, 0.0593, 0.8041],
        [0.0268, 0.6153, 0.6731],
        [0.1644, 0.1345, 0.6655]])


In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.8474,  0.6569,  1.3365],
        [ 2.2769, -0.3193,  0.7688],
        [-1.6104, -0.6322,  1.9083],
        [ 0.5945,  0.9405, -1.0940],
        [-1.1254, -0.8179,  0.1125]])


In [10]:
print(x.size())

torch.Size([5, 3])


#### Tensors operations

In [13]:
y = torch.randn_like(x, dtype=torch.float) 
print(torch.add(x, y))

tensor([[ 0.2006,  2.1374,  1.2752],
        [ 1.6628, -0.2835,  1.8440],
        [-1.3281, -2.5315,  0.0241],
        [ 0.9772,  2.2147, -2.0587],
        [ 0.6177, -0.4970,  0.4687]])


In [15]:
result = torch.empty(5, 3)
torch.sub(x, y, out=result)
print(result)

tensor([[ 1.4941, -0.8236,  1.3978],
        [ 2.8910, -0.3550, -0.3064],
        [-1.8927,  1.2671,  3.7926],
        [ 0.2119, -0.3338, -0.1292],
        [-2.8686, -1.1388, -0.2438]])


In [16]:
print(x[:, 1])

tensor([ 0.6569, -0.3193, -0.6322,  0.9405, -0.8179])


In [17]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
x = torch.randn(1)
print(x)
print(x.item()) # get value as number

tensor([0.5791])
0.5790753364562988


#### Tensors bridge to numpy

In [20]:
a = torch.ones(5)
print(a)
b = a.numpy() # numpy view to a (reference)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [21]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [24]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a) # data copied (value transfer)
np.add(a, 1, out=a)
print(a)
print(b)
a = a + 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


#### Load in GPU

In [25]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
    

### Autograd of tensors